# Generated by Django 5.0 on 2024-01-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='age',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='bmi',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='fpg',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='ht',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='pardimen',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='result',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='wtoh',
            field=models.IntegerField(default=''),
        ),
    ]
