# Generated by Django 5.0 on 2024-01-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_dmalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='DmBefore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bq1', models.IntegerField(default='')),
                ('bq2', models.IntegerField(default='')),
                ('bq3', models.IntegerField(default='')),
                ('bq4', models.IntegerField(default='')),
                ('bq5', models.IntegerField(default='')),
                ('bq6', models.IntegerField(default='')),
                ('bq7', models.IntegerField(default='')),
                ('bq8', models.IntegerField(default='')),
                ('bq9', models.IntegerField(default='')),
                ('bq10', models.IntegerField(default='')),
                ('bresult', models.IntegerField(default='0', null=True)),
            ],
        ),
    ]
