# Generated by Django 5.0 on 2024-01-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_dmbefore'),
    ]

    operations = [
        migrations.CreateModel(
            name='DmAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aq1', models.IntegerField(default='')),
                ('aq2', models.IntegerField(default='')),
                ('aq3', models.IntegerField(default='')),
                ('aq4', models.IntegerField(default='')),
                ('aq5', models.IntegerField(default='')),
                ('aq6', models.IntegerField(default='')),
                ('aq7', models.IntegerField(default='')),
                ('aq8', models.IntegerField(default='')),
                ('aq9', models.IntegerField(default='')),
                ('aq10', models.IntegerField(default='')),
                ('aresult', models.IntegerField(default='0', null=True)),
            ],
        ),
    ]
