# Generated by Django 5.0 on 2024-01-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_dmafter'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='uname',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
