# Generated by Django 5.0 on 2024-01-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_dmbefore_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmafter',
            name='uname',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
