# Generated by Django 5.0 on 2024-01-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_dmafter_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='uname',
            field=models.CharField(default='', max_length=40, null=True),
        ),
    ]
