# Generated by Django 5.0 on 2024-01-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_dmafter_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='satisfied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sq1', models.IntegerField(default='')),
                ('sq2', models.IntegerField(default='')),
                ('sq3', models.IntegerField(default='')),
                ('sq4', models.IntegerField(default='')),
                ('sq5', models.IntegerField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sresultdate', models.IntegerField(default='0', null=True)),
            ],
        ),
    ]
