# Generated by Django 5.0 on 2024-01-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_sresultdate_satisfied_sresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisfied',
            name='advice',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
