# Generated by Django 5.0 on 2024-01-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_satisfied_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmafter',
            name='before2',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
