# Generated by Django 5.0 on 2024-01-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_dmafter_before2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmafter',
            name='uname',
            field=models.CharField(max_length=40, null=True, verbose_name='name'),
        ),
    ]
