# Generated by Django 5.0 on 2024-01-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_dmafter_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmafter',
            name='uname',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
