# Generated by Django 5.0 on 2024-01-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_dmafter_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmafter',
            name='alertresult',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='dmafter',
            name='riskresult',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
